itest/opstackl2/op_e2e_test.go
itest/opstackl2/op_test_manager.go

This is a small PR to fix several missed comments in https://github.com/babylonlabs-io/finality-provider/pull/26
```
make lint
make test-e2e-op
```

test: finality gadget itest fix comments

---

clientcontroller/opstackl2/consumer.go

This PR updated the implementation of activated height which queries the BTC staking activated timestamp via the finality gadget grpc, and then converted it to the L2 block number.
Content https://github.com/babylonchain/finality-provider/issues/432
```
make lint
make test
make test-e2e-op
```

chore: update query activated height

---

clientcontroller/opstackl2/consumer.go
finality-provider/config/opstackl2.go
finality-provider/service/fp_instance.go
itest/opstackl2/README.md
itest/opstackl2/op_e2e_test.go
itest/opstackl2/op_test_manager.go

context in [#496](https://github.com/babylonchain/finality-provider/issues/496)
This pr implements the logic of querying voting power in Op. 
> instead of querying the exact voting power, the FP queries BTC delegations page by page, and if there is >=1 active BTC delegation, then it can vote.
```
make test-e2e-op
```

Feat: impl QueryFinalityProviderHasPower in consumer chain

---

finality-provider/config/config.go
finality-provider/service/app.go

The goal here was to make life easier for finality provider operators to be able to turn on the finality provider before the consumer node is available and wait for that node to become available for `MinutesToWaitForConsumer` minutes

chore: add retry for consumer chain to become available

---

clientcontroller/babylon.go
finality-provider/cmd/fpd/daemon/start.go
finality-provider/config/config.go
finality-provider/service/app.go
finality-provider/service/chain_poller_test.go
finality-provider/service/fp_manager.go
finality-provider/store/fpstore.go
finality-provider/store/storedfp.go

- Removed previous `MinutesToWaitForConsumer` added in #50 since it was not good enough to wait for the chain to be up, without starting the fpd server to receive fpd creation 
- Add new loop that verifies the FP status on chain and update it accordingly (before it was only one time at startup)
- Add check for keyring key is valid at start of `NewBabylonController` to avoid panic at `mustGetTxSigner`

chore: keep sync fp status

---

itest/container/config.go
itest/container/container.go
itest/test_manager.go
testutil/version.go

Ensures that our e2e tests version use a correct version of babylond from go.mod

chore(e2e): parse go mod for babylond version

---

go.mod
go.sum
tools/go.mod
tools/go.sum

After this PR, we can tag `euphrates-0.5.0-rc.0` for FP

chore: use 0.5.0 rc version of Babylon

---

finality-provider/service/fp_instance.go
itest/babylon/babylon_e2e_test.go
itest/opstackl2/op_test_manager.go

cherry-pick for the PR https://github.com/babylonlabs-io/finality-provider/pull/57
Also, this PR updates Babylon e2e test `TestFinalityProviderLifeCycle` to verify the batch processing blocks from the poller channel.
```
make lint
make test
make test-e2e-babylon
```

feat: batch processing blocks from the poller channel

---

.github/workflows/ci.yml
.github/workflows/publish.yml
clientcontroller/babylon.go
clientcontroller/interface.go
eotsmanager/cmd/eotsd/daemon/sign.go
eotsmanager/service/server.go
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/cmd/fpd/daemon/export.go
finality-provider/config/config.go
finality-provider/service/client/rpcclient.go
finality-provider/service/eots_manager_adapter.go
finality-provider/service/fastsync_test.go
finality-provider/service/fp_instance.go
finality-provider/service/server.go
log/log.go
metrics/server.go
testutil/mocks/babylon.go

This update involves:
- Enabling gosec in the github workflow and updating the github workflow versions.
- Update the codebase to fix findings from gosec. Highlights:
- Some unhandled errors
- Config types allowed for very large values. For example, the retry intervals and the commit gaps allowed for uint64. All values related to block sizes were left to uint64, but the others were reduced to uint32.
- Prometheus server protection against Slowloris

chore: Enable gosec and fix findings

---

finality-provider/cmd/fpd/daemon/start.go
finality-provider/config/config.go
finality-provider/service/app.go
finality-provider/service/app_test.go
finality-provider/service/fp_instance.go
finality-provider/service/fp_instance_test.go
finality-provider/service/fp_manager.go
finality-provider/service/fp_manager_test.go
finality-provider/service/rpcserver.go
finality-provider/store/storedfp.go
itest/e2e_test.go
itest/test_manager.go

This PR partly addresses https://github.com/babylonlabs-io/finality-provider/issues/34 by disallowing running multiple fp instances within the fp manager. Keyring level improvement will be done in a separate PR to address #63. Notable changes in this PR:
1. Remove `MaxNumFinalityProviders` from config as it is not applicable
2. If `--eots-pk` is not specified in `fpd start`, fp app will start without any fp instances. To run a fp instance, `--eots-pk` must be given
3. fp manager only keeps a single fp instance instead of a map

chore: Remove running multiple fp instances support

---

.github/workflows/changelog-reminder.yml
.github/workflows/ci.yml
.gitignore
.goreleaser.yml
CHANGELOG.md
Makefile

This PR
- sets up Go releaser for Babylon. Currently it only supports linux amd64. Other targets will be supported in the future. To test locally, run `make release-snapshot`
- moves changelog reminder out from the CI flow

ci: add goreleaser setup and move out changelog reminder

---

.github/workflows/ci.yml
Makefile
itest/opstackl2/README.md

This PR:
* adds a step to the CI `e2e_op` job to set up the devnet data for OP e2e tests, addressing the issue where the devnet data does not exist. https://github.com/babylonlabs-io/finality-provider/pull/76#issuecomment-2382903913
* removes the FILTER to fix the  `e2e_op` job issue: "no test to run"
* adds a new make target to support for the filter
To trigger the CI to check if the op e2e tests work fine.

fix: CI failed to run the op e2e tests

---

.github/workflows/publish.yml

not sure why it didn't detect in https://github.com/babylonlabs-io/finality-provider/pull/95
I have no idea why it's failing but I noticed this formatting issue

nit: fix workflow syntax issue

---

finality-provider/config/opstackl2.go

The finality gadget is a gRPC service, its rpc should be a host or ip:port without the `scheme://`, so we can't use `url.Parse` to validate it.
FP should be launched with the `BabylonFinalityGadgetRpc=135.225.83.181:50051`

fix: remove the url check for fg rpc

---

clientcontroller/babylon/babylon.go
clientcontroller/babylon/consumer.go
itest/opstackl2/op_test_manager.go

The previous fix #142 only fixed the error handler for babylon controller chain other than the cosumer chain. This PR addressed it.

fix: Voting power query error handler for consumer chain

---

CHANGELOG.md
finality-provider/service/app.go

chore: Use sign schnorr instead of getting private key from EOTS manager

---

CHANGELOG.md
finality-provider/service/chain_poller.go

Closes #157 by removing the validation that the start height should be higher than the current tip height of the consumer chain.
The validation can be removed as the poller will start until btc staking starts (at least one finality provider has voting power)

fix: Remove start height validation

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/keys.go
eotsmanager/cmd/eotsd/daemon/keysadd.go

- Respects the output flag of text or json
Closes https://github.com/babylonlabs-io/finality-provider/issues/156

fix: eotsd `--output` flag 

---

CHANGELOG.md
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/service/app.go
finality-provider/service/app_test.go
finality-provider/service/fp_instance_test.go
finality-provider/service/rpcserver.go
itest/test_manager.go

Closes #162. Also marked some flags as required:
- eots-pk
- chain-id
- key-name
- commission
- moniker

chore: Remove key creation in `create-finality-provider`

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/root.go
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/cmd/fpd/main.go
version/cmd.go

```
lazar@Lazars-MacBook-Pro finality-provider % ./build/eotsd v
Version:       0.12.0-9-g965510a
Git Commit:    965510a
Git Timestamp: 2024-11-28T12:51:34Z
```
[tracking issue](https://github.com/babylonlabs-io/finality-provider/issues/174)

chore(cmd): adds eotsd version command

---

CHANGELOG.md
clientcontroller/babylon.go
clientcontroller/interface.go
finality-provider/service/app_test.go
finality-provider/service/fp_instance.go
finality-provider/service/fp_instance_test.go
finality-provider/service/fp_manager_test.go
go.mod
go.sum
itest/container/config.go
testutil/mocks/babylon.go

Closes #119 by adding highest voted height into consideration of determining start height. This implements the finality provider part of [ADR-35](https://github.com/babylonlabs-io/pm/blob/main/adr/adr-035-slashing-protection.md)

chore(adr-35): Refactor determining start height

---

itest/opstackl2/op_e2e_test.go
itest/opstackl2/op_test_manager.go
itest/test-manager/base_test_manager.go

This is the third refactor https://github.com/babylonlabs-io/finality-provider/pull/178 PR to implement the basic setup for FP registration and BTC delegation.
```
make lint
make test-e2e-op
...
op_test_manager.go:412: [13:38:17.854] Registered Finality Provider 6306502a53110350adfebcacfdc25f66ab14fbe27d41f7661163a53d1f3c43a3 for chain-test
2024-12-03T13:38:18.414+0800    INFO    eotsmanager/localmanager.go:136 successfully created an EOTS key        {"key name": "test-spending-key", "pk": "d442e852dd78b732da94cc45a92bfd7667cbd36d16e0a028d173523727cc9dc5"}
2024-12-03T13:38:18.464+0800    INFO    service/app.go:444      successfully created a finality-provider        {"btc_pk": "d442e852dd78b732da94cc45a92bfd7667cbd36d16e0a028d173523727cc9dc5", "addr": …
```

chore: refactor op e2e tests - part 3

---

CHANGELOG.md
finality-provider/service/fp_instance_test.go

For numPubRand ≤ 1000, the growth appears roughly linear, with execution time increasing by similar factors as numPubRand
---
Benchmark ran on M3 Pro.
numPubRand | Iterations (b.N) | Time per Iteration (ns/op) | Approx. Time (ms) | Approx. Time (s)
-- | -- | -- | -- | --
10 | 38 | 29,210,366 | ~29.2 ms | ~0.03 s
50 | 16 | 68,297,312 | ~68.3 ms | ~0.07 s
100 | 9 | 120,456,028 | ~120.5 ms | ~0.12 s
200 | 5 | 224,715,767 | ~224.7 ms | ~0.22 s
500 | 2 | 536,105,584 | ~536.1 ms | ~0.54 s
1,000 | 1 | 1,056,664,416 | ~1.1 s | ~1.1 s
5,000 | 1 | 5,159,288,750 | ~5.2 s | ~5.2 s
10,000 | 1 | 10,353,431,958 | ~10.4 s | ~10.4 s
25,000 | 1 | 26,828,946,167 | ~26.8 s | ~26.8 s
50,000 | 1 | 53,123,792,875 | ~53.1 s | ~53.1 s
75,000 | 1 | 156,188,836,166 | ~156.2 s | ~2.6 m
100,000 | 1 | 211,468,613,458 …

chore: benchmark pub randomness commit 

---

CHANGELOG.md
finality-provider/service/app.go
finality-provider/service/app_test.go
finality-provider/service/event_loops.go
finality-provider/service/fp_instance.go
finality-provider/service/fp_store_adapter.go
finality-provider/service/rpcserver.go

Closes #122 by introducing a separate event loop for unjailing requests

chore: Not block unjailing

---

CHANGELOG.md
finality-provider/cmd/fpd/daemon/tx.go

Adds support for invoking `NewWithdrawRewardCmd` and `NewSetWithdrawAddressCmd`
[Closes](https://github.com/babylonlabs-io/finality-provider/issues/13)

chore: x/incentive cmds

---

CHANGELOG.md
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/cmd/fpd/daemon/flags.go
itest/e2e_test.go

Alternative to passing in flags, the operator would provide a JSON file.
[Closes](https://github.com/babylonlabs-io/finality-provider/issues/14)

chore: create fp from json

---

CHANGELOG.md
clientcontroller/babylon.go
finality-provider/config/config.go
finality-provider/service/app.go
finality-provider/service/app_test.go
finality-provider/service/event_loops.go
finality-provider/store/fpstore.go

Closes #191. In particular, this PR:
- removed the loop for syncing fp status but syncing in the main thread during fp app initiation.
- the loop is no longer needed as we have decided no fp will be registered via chain upgrade
- we still need syncing status during initiation in case the fp is slashed or jailed
- in `monitorStatusUpdate`, the check for jailing and slashing is removed. This is because the removal of voting power due to slashing or jailing happens in the next block. Countering jailing and slashing in the loop will cause the fp to not vote when it still have voting power for the current block

chore: Remove sync fp status loop

---

.github/workflows/ci.yml
finality-provider/config/config.go

fix a small bug which was introduced in https://github.com/babylonlabs-io/finality-provider/pull/155
this caused FP failed to start
```
bash-5.1$ fpd start
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
Error: failed to load configuration: /home/finality-provider/.fpd/fpd.conf:6: Invalid value `OPStackL2' for option `--chaintype'. Allowed values are: 
Usage:
fpd start [flags]
```
tested with a new docker image created by CI
```
babylonlabs/finality-provider:9fcbde4fdacd26de256a944dedacb645826c2e9e
```
and it doesn't have this error anymore

fix: ChainType choices (to support consumer chains)

---

README.md

There is invalid link in the document.
Fix invalid link in the document. The commit explains which link is invalid and how it is fixed.

docs: fix invalid link README.md

---

.github/workflows/ci.yml
finality-provider/service/fp_instance.go

we found an issue in our OP devnet that finality sigs were submitted very slow. the root cause is we shouldn't wait 300 seconds in the first iteration in the for loop inside `retrySubmitSigsUntilFinalized()`
more context: https://github.com/babylonlabs-io/finality-provider/pull/155#discussion_r1881988164
tested in our devnet with the new image
set `PollInterval` to 0.5 sec and see how it "fast synced" to the latest block

fix: shouldn't wait `SubmissionRetryInterval` at the first iteration

---

CHANGELOG.md
finality-provider/service/fp_instance.go

https://github.com/babylonlabs-io/finality-provider/pull/217/

backport: #217 - shouldn't wait SubmissionRetryInterval at the first iteration 

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/keys.go

feat: add save key on mapping after import of keys

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/keys.go
eotsmanager/cmd/eotsd/daemon/root.go
eotsmanager/localmanager.go
eotsmanager/store/eotsstore.go
eotsmanager/store/eotsstore_test.go
itest/e2e_test.go
itest/test_manager.go

Adds `eotsd ls` command which prints all keys from DB
[closes](https://github.com/babylonlabs-io/finality-provider/issues/229)

feat: list all keys in store

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/start.go
eotsmanager/cmd/eotsd/main.go
eotsmanager/service/server.go
finality-provider/cmd/fpd/daemon/start.go
finality-provider/cmd/fpd/main.go
finality-provider/service/server.go
itest/e2e_test.go
itest/eotsmanager_handler.go
itest/test_manager.go
testutil/port.go

This PR removes the usage of `signal.Interceptor` and uses Go's idiomatic `context` to handle cancellations. This enables us to run e2e tests in parallel (almost 4x faster).
```
//old-time
ok      github.com/babylonlabs-io/finality-provider/itest       548.976s
// new time
ok      github.com/babylonlabs-io/finality-provider/itest       139.579s
```
Time in GH action `9m 58s` vs `3m 24s`
Closes #219

feat: rm interceptors and use context

---

CHANGELOG.md
finality-provider/service/fp_instance.go
finality-provider/service/fp_instance_test.go

Closes https://github.com/babylonlabs-io/finality-provider/issues/253.
The poller should start from the `lastFinalizedHeight` other than `lastVotedHeight`. This is to deal with cases where the gap between the two heights is large so that the delay of catching up could cause jailing.
This change will not give up many rewards because rewards are not assigned to late votes due to [ADR](https://github.com/babylonlabs-io/pm/blob/main/adr/adr-039-finality-voting-rewarding.md).

chore: Refactor to start from the last finalized height

---

CHANGELOG.md
finality-provider/service/fp_instance.go
finality-provider/service/fp_instance_test.go

Closes https://github.com/babylonlabs-io/finality-provider/issues/253.
The poller should start from the `lastFinalizedHeight` other than `lastVotedHeight`. This is to deal with cases where the gap between the two heights is large so that the delay of catching up could cause jailing.
This change will not give up many rewards because rewards are not assigned to late votes due to
[ADR](https://github.com/babylonlabs-io/pm/blob/main/adr/adr-039-finality-voting-rewarding.md).

[backport] chore: Refactor to start from the last finalized height (#257)

---

CHANGELOG.md
docs/finality-provider-operation.md
finality-provider/cmd/cmd_test.go
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/cmd/fpd/daemon/start.go
finality-provider/service/app.go
itest/test_manager.go

Closes #289. With this pr, the `fpd start` flow becomes the follows:
- If --eots-pk is specified, start the specified fp instance. Otherwise,
- if no fp records found from db, start the daemon and show logs asking for registration
- if there's one fp record found from db, start the daemon with the fp
- if there are multiple fp record found from db, fail the cmd execution asking for set of --eots-pk

[backport] chore: Improve fpd start (#294)

---

CHANGELOG.md
eotsmanager/randgenerator/randgenerator.go

Closes https://github.com/babylonlabs-io/pm/issues/191

chore: fix small bias in EOTS private key generation

---

finality-provider/service/chain_poller.go

When chain poller try to got new blocks, it will count a `failedCycles`, when it > `maxFailedCycles`, the finality-provider will exit by:
```go
if failedCycles > maxFailedCycles {
cp.logger.Fatal("the poller has reached the max failed cycles, exiting")
}
```
BUT in chain poller, when the poller no got new blocks during `PollInterval`, it will also add `failedCycles`.
So when the chain no produce blocks in `PollInterval` * `maxFailedCycles`, the fp will exit.
For some chain, it may no produce blocks when no new tx, and in some times, the chain will pause by chain upgrade, so it will make the fp exit by the error.
So in this PR, we make `failedCycles ` no update when no new blocks.

fix: no add failed cycles count when chain poller no found new blocks

---

CHANGELOG.md
clientcontroller/cosmwasm/consumer.go

Part of https://github.com/babylonlabs-io/babylon-integration-deployment/pull/32
- ensure `startHeight <= endHeight` for range queries
- avoid unnecessary conversions between `sdk.AccAddress` and string address

chore: fix CosmWasm controller 

---

CHANGELOG.md
finality-provider/service/chain_poller.go

Part of https://github.com/babylonlabs-io/babylon-integration-deployment/pull/32
`latestBlockHeight` can be the current height if there is no new block during this polling iteration, but `blockToRetrieve` is set `cp.NextHeight()` , meaning that `blockToRetrieve` can be bigger than `latestBlockHeight` by `1`.
This PR adds a check on `blockToRetrieve > lastestBlockHeight`, and skips with some logging if this occurs

poller: skip if no new block is polled

---

CHANGELOG.md
finality-provider/service/chain_poller.go

Part of
https://github.com/babylonlabs-io/babylon-integration-deployment/pull/32
`latestBlockHeight` can be the current height if there is no new block during this polling iteration, but `blockToRetrieve` is set `cp.NextHeight()` , meaning that `blockToRetrieve` can be bigger than `latestBlockHeight` by `1`.
This PR adds a check on `blockToRetrieve > lastestBlockHeight`, and skips with some logging if this occurs

[Backport] poller: skip if no new block is polled (#333)

---

CHANGELOG.md
clientcontroller/babylon/consumer.go
docs/finality-provider-operation.md
finality-provider/cmd/fpd/daemon/recover_proof.go
finality-provider/cmd/fpd/main.go
finality-provider/config/db.go
finality-provider/service/fp_instance.go
itest/babylon/babylon_e2e_test.go
itest/eotsmanager_handler.go

Closes #293. In particular, this PR:
- added a new cmd `recover-rand-proof --start-height` which checks the randomness commit on Babylon, re-generate randomness proof, and stores it in db.
- to check the randomness commit on babylon, a new query `QueryPublicRandCommitList` is added to babylon consumer client
- Note that this cmd currently only works for babylon consumer chain
- updated operational doc

feat: Add recover proof cmd

---

CHANGELOG.md
clientcontroller/babylon.go
docs/finality-provider-operation.md
finality-provider/cmd/fpd/daemon/recover_proof.go
finality-provider/cmd/fpd/main.go
finality-provider/config/db.go
finality-provider/service/fp_instance.go
itest/e2e_test.go
itest/eotsmanager_handler.go
types/pub_rand_commit.go

Closes #293. In particular, this PR:
- added a new cmd `recover-rand-proof --start-height` which checks the randomness commit on Babylon, re-generate randomness proof, and stores it in db.
- to check the randomness commit on babylon, a new query `QueryPublicRandCommitList` is added to babylon consumer client
- Note that this cmd currently only works for babylon consumer chain
- updated operational doc

[backport] feat: Add recover proof cmd (#351)

---

CHANGELOG.md
docs/hmac-security.md
eotsmanager/client/hmac.go
eotsmanager/client/rpcclient.go
eotsmanager/client/secrets.go
eotsmanager/cmd/eotsd/daemon/keys.go
eotsmanager/service/hmac.go
eotsmanager/service/hmac_test.go
eotsmanager/service/server.go
finality-provider/cmd/fpd/daemon/commit_pr.go
finality-provider/cmd/fpd/daemon/recover_proof.go
finality-provider/service/eots_manager_adapter.go
itest/babylon/babylon_e2e_test.go
itest/babylon/babylon_test_manager.go
itest/babylon/hmac_e2e_test.go
itest/cosmwasm/bcd/bcd_test_manager.go
itest/eotsmanager_handler.go
itest/test-manager/base_test_manager.go

Check full proto names of the excluded from hmac methods instead of with suffix. Removes the requirement for ENV variable setting and only keeps config settings.

fix: check excluded methods with full names instead of prefixes and remove env variable requirement

---

CHANGELOG.md
docs/commit-pub-rand.md
docs/finality-provider-operation.md
finality-provider/config/config.go
finality-provider/config/config_test.go
finality-provider/service/fp_instance.go
itest/test_manager.go

The point of this PR is to ensure that users cannot insert config values that will cause the fp to crash or jailed. Notable changes are:
- Remove config items NumPubRandMax, TimestampingDelayBlocks, RandomnessCommitInterval but hardcode them as they are critical ones that should not be changeable. TimestampingDelayBlocks is calculated based on w=300 and babylon block production time of 10s
- Add validations to config items. Note that MinPubRand to ensure that a commit can pass verification on Babylon side.

chore: Modify default config and add validation

---

CHANGELOG.md
finality-provider/store/fpstore.go

fix: handle uninitialized commissionInfo when editing fp

---

CHANGELOG.md
finality-provider/service/fp_instance.go
finality-provider/service/fp_store_adapter.go
metrics/fp_collectors.go

Introduces a new metric `fp_voted_height` so we can query historically voted heights.
func `RecordFpVoteTime` wasn't getting called, and it's important for `fp_seconds_since_last_vote`

chore: metrics for votes

---

README.md
docs/finality-provider-operation.md
docs/fp-core.md
docs/hmac-security.md

This PR improves the finality provider doc in general. It covers the following changes:
- Rename Babylon, Babylon network, Babylon blockchain to Babylon Genesis
- Improve `Rewards and Refunding`
- Remove Refunding part
- Add `6.3. Set Up Operation Key` to avoid confusion
- Other small edits

Update finality provider docs

---

README.md
docs/finality-provider-operation.md
docs/fp-core.md
docs/hmac-security.md

This PR improves the finality provider doc in general. It covers the following changes:
- Rename Babylon, Babylon network, Babylon blockchain to Babylon Genesis
- Improve `Rewards and Refunding`
- Remove Refunding part
- Add `6.3. Set Up Operation Key` to avoid confusion
- Other small edits

[Backport] Update finality provider doc

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/start.go
eotsmanager/config/config.go

24 Incomplete passphrase validation for keyring backends creates a security risk

chore: validate keyring-backend in cfg (#489) [backport]

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/keys.go
eotsmanager/cmd/eotsd/daemon/keysadd.go
eotsmanager/cmd/eotsd/daemon/unlock.go
eotsmanager/store/eotsstore.go
eotsmanager/store/eotsstore_test.go
eotsmanager/store/errors.go

- ignores key already exists err, as this is already handled by keyring
- propagates `client.Context` so that we don't need to reinitialize keyring over and over again but share the ctx

chore: improve keyring handling in add keys command (#493)

---

CHANGELOG.md
bsn/rollup-finality-provider/clientcontroller/consumer.go
bsn/rollup-finality-provider/config/config.go
bsn/rollup-finality-provider/e2e/op_test_manager.go
go.mod
go.sum

Resolves #503 
This PR removes the dependency to finality gadget in `rollup-fpd`, removes certain unused varaibles/functions, and makes certain functions private.

rollup: remove dependency to finality gadget

---

CHANGELOG.md
go.mod
go.sum
itest/container/config.go

We want fp v2 to be compatible with bbn v2, this bump makes that possible

chore: bump bbn for v2 compatibility

---

CHANGELOG.md
bsn/cosmos/e2e/bcd_consumer_e2e_test.go
bsn/cosmos/e2e/bcd_handler.go
bsn/cosmos/e2e/bcd_test_manager.go

Cosmos e2e tests take way too long to run sequentially, now makes them parallel
closes #599

chore: make cosmos e2e run in parallel

---

CHANGELOG.md
bsn/rollup/config/config.go

Change the default to 100 to avoid rate limits

chore: default poll size rollup (#610)

---

CHANGELOG.md
bsn/rollup/cmd/rollup-fpd/daemon/recover_proof.go
finality-provider/service/pub_rand_store_adapter.go
finality-provider/service/rand_committer.go
finality-provider/store/pub_rand.go

Remove duplicate methods, use variadic options.
Closes https://github.com/babylonlabs-io/finality-provider/issues/635

chore: unify proof building (#634)

---

CHANGELOG.md
finality-provider/service/finality_submitter.go

- bbn and cosmos fp have consecutive heights to vote, proof building can be reverted to the original impl, for rollups we use dedicated rollup-finality-submitter instance

chore: improve proof batch building
