babylonlabs-io/finality-provider

.github/workflows/backport.yml
.github/workflows/ci.yml
.github/workflows/goreleaser.yml
.github/workflows/publish.yml
CHANGELOG.md

Also created an empty changelog and bumped the .github dependency

ci: GH actions for goreleaser, changelog reminder, and backport

---

.github/workflows/publish.yml

chore: update CI to publish docker images for base/consumer-chain-support

---

.github/workflows/publish.yml

https://github.com/babylonlabs-io/finality-provider/pull/93

backport: update CI to publish docker images for base branch

---

.github/workflows/publish.yml

chore: fix CI missing OP devnet setup

---

clientcontroller/opstackl2/msg.go

chore: remove unused struct

---

CHANGELOG.md
itest/test_manager.go

This pr fixes minor issue of itest in chore/backport CI.

Fix: fix itest config issue

---

CHANGELOG.md
clientcontroller/babylon.go
finality-provider/service/app.go
finality-provider/service/app_test.go

fix: Ignore voting power not updated error

---

CHANGELOG.md
docs/finality-provider-operation.md
finality-provider/cmd/fpd/daemon/daemon_commands.go

chore: Change `btc_pk` text to `eots_pk`

---

CHANGELOG.md
docs/finality-provider-operation.md
finality-provider/service/app.go
finality-provider/service/fp_instance.go
itest/e2e_test.go
itest/eotsmanager_handler.go
itest/test_manager.go

chore: add multiple fpd connecting to one eotsd in e2e tests

---

CHANGELOG.md
go.mod
go.sum

chore: bump babylon to v1.0.0-rc.1

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/keys.go

cherry pick a69c0530f5e2e289bc890593b93ea67a18f6ca97

chore: release v0.14.0

---

CHANGELOG.md
finality-provider/service/app.go
itest/test_manager.go

Starts the fp instance fp register

fix: start fp after register (#246) [backport]

---

eotsmanager/cmd/eotsd/daemon/pop.go
eotsmanager/cmd/eotsd/daemon/pop_test.go
eotsmanager/cmd/eotsd/daemon/sign_test.go
eotsmanager/cmd/eotsd/main.go
eotsmanager/localmanager.go

chore: v0.4.2 backport of #284

---

CHANGELOG.md
finality-provider/service/chain_poller.go
finality-provider/service/chain_poller_test.go
finality-provider/service/test_flakiness.sh

chore: Remove skip height

---

eotsmanager/cmd/eotsd/daemon/pop.go
eotsmanager/cmd/eotsd/daemon/pop_test.go

#297 
Tag v0.4.3 should be pushed after this merge

backport #297 to V0.4.x

---

CHANGELOG.md
finality-provider/service/fp_instance.go

fix: increment `fp_total_failed_votes` if block is finalized

---

finality-provider/config/config.go
finality-provider/config/poller.go
itest/babylon/babylon_test_manager.go

This PR fixes some bugs found through local deployment https://github.com/babylonlabs-io/babylon-integration-deployment/pull/32

fix: config validation and flaky babylon e2e

---

CHANGELOG.md
docs/finality-provider-operation.md
finality-provider/cmd/fpd/main.go

Closes https://github.com/babylonlabs-io/finality-provider/issues/352

chore(incentive): add reward gauges query cmd

---

CHANGELOG.md
docs/finality-provider-operation.md
finality-provider/cmd/fpd/main.go

Closes https://github.com/babylonlabs-io/finality-provider/issues/352

backport: chore(incentive): add reward gauges query cmd (#356)

---

finality-provider/config/poller.go

The issue only exists in `release/v1.x` branch

fix: fpd config validate

---

README.md
docs/finality-provider-operation.md
docs/slashing-protection.md

doc: Add slashing protection doc

---

README.md
docs/finality-provider-operation.md
docs/slashing-protection.md

[backport] doc: Add slashing protection doc (#377)

---

docs/slashing-protection.md

This PR adds security tips for preventing double-sign

[backport] doc: Update slashing protection doc (#379)

---

CHANGELOG.md
clientcontroller/babylon.go

[backport] fix: Add expected errors to when sending finality signatures #372

---

CHANGELOG.md
finality-provider/store/pub_rand.go
finality-provider/store/pub_rand_test.go

chore: overwrite randomness proof (#397)

---

CHANGELOG.md
finality-provider/cmd/fpd/daemon/daemon_commands.go

chore: rm default value for app hash flag

---

CHANGELOG.md
eotsmanager/cmd/eotsd/daemon/root.go
eotsmanager/cmd/eotsd/daemon/store.go
eotsmanager/localmanager.go
eotsmanager/store/eotsstore.go
eotsmanager/store/eotsstore_test.go
itest/e2e_test.go
itest/eotsmanager_handler.go

chore: rollback sign records from eots store (#410) [backport]

---

CHANGELOG.md
go.mod
go.sum

chore: Bump babylon v1.0.0

---

CHANGELOG.md
clientcontroller/api/interface.go
clientcontroller/babylon/babylon.go
clientcontroller/babylon/consumer.go
clientcontroller/factory.go
finality-provider/cmd/fpd/daemon/recover_proof.go
finality-provider/config/config.go
itest/babylon/babylon_test_manager.go
itest/cosmwasm/bcd/bcd_test_manager.go
itest/opstackl2/op_test_manager.go
itest/utils.go

Closes #432. This is not used in real-time running.

chore: remove bitcoinnetwork config

---

CHANGELOG.md
clientcontroller/babylon.go
clientcontroller/interface.go
finality-provider/cmd/fpd/daemon/commit_pr.go
finality-provider/cmd/fpd/daemon/recover_proof.go
finality-provider/config/config.go
finality-provider/service/app.go
itest/test_manager.go

Closes #432. This is not used in real-time running.

[backport] Remove unused bitcoinnetwork config

---

CHANGELOG.md
eotsmanager/service/rpcserver.go
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/service/eots_manager_adapter.go
finality-provider/service/errors.go
finality-provider/service/fp_instance.go
go.mod
go.sum
itest/babylon/babylon_e2e_test.go
itest/babylon/babylon_test_manager.go

Closes https://github.com/babylonlabs-io/pm/issues/319

chore: ignore double sign error

---

CHANGELOG.md
eotsmanager/service/rpcserver.go
finality-provider/cmd/fpd/daemon/daemon_commands.go
finality-provider/service/eots_manager_adapter.go
finality-provider/service/errors.go
finality-provider/service/fp_instance.go
go.mod
go.sum
itest/e2e_test.go
itest/test_manager.go

Closes https://github.com/babylonlabs-io/pm/issues/319

[backport] Ignore failed precondition err

---

docs/finality-provider-operation.md

[backport] doc: add key comparison section

---

CHANGELOG.md
finality-provider/cmd/fpd/daemon/commit_pr.go
finality-provider/service/fp_instance.go
finality-provider/service/pub_rand_store_adapter.go
finality-provider/store/pub_rand.go
itest/e2e_test.go

To commit 100k pub rand takes: `8m11s`

chore: adds e2e for unsafe commit pub rand (#469)

---

CHANGELOG.md
finality-provider/config/config.go
finality-provider/service/app.go
finality-provider/service/eots_manager_adapter.go
finality-provider/service/fp_instance.go
finality-provider/signingcontext/builder.go

Reimplements the signingcotext from babylon

chore: signing context

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.golangci.yml
CHANGELOG.md
Dockerfile
bsn/cosmos/e2e/bcd_consumer_e2e_test.go
bsn/cosmos/e2e/bcd_handler.go
bsn/rollup/e2e/rollup_e2e_test.go
eotsmanager/client/hmac_test.go
eotsmanager/cmd/eotsd/daemon/pop_test.go
eotsmanager/service/hmac_test.go
finality-provider/cmd/fpd/clientctx/cmd_test.go
finality-provider/service/app_test.go
finality-provider/service/chain_poller_test.go
finality-provider/service/fp_instance_test.go
finality-provider/service/fp_test_helper.go
go.mod
itest/babylon/babylon_e2e_test.go
itest/babylon/babylon_test_manager.go
itest/babylon/hmac_e2e_test.go
version/cmd.go

chore: bump go 1.24

---

CHANGELOG.md
bsn/cosmos/e2e/bcd_consumer_e2e_test.go
bsn/cosmos/e2e/bcd_test_manager.go
finality-provider/service/finality_submitter.go
finality-provider/service/fp_instance.go
itest/babylon/babylon_e2e_test.go

closes https://github.com/babylonlabs-io/finality-provider/issues/574

chore: prevent flappy e2e

---

CHANGELOG.md
bsn/cosmos/config/cosmwasm.go
bsn/cosmos/cosmwasmclient/config/config.go

chore: change default cosmwasm cfg values

---

CHANGELOG.md
Makefile
bsn/cosmos/e2e/bcd_consumer_e2e_test.go
bsn/cosmos/e2e/bcd_handler.go
bsn/cosmos/e2e/bcd_test_manager.go

from `22m` -> `12`.
address flakiness as well

chore: faster bcd e2e
